### PR TITLE
Add support for air filter and error code

### PR DESCRIPTION
**Pull request by amitfin**

### CODE REVIEW

**Comment by amitfin** [comment]
The draft of the corresponding Home Assistant PR can be found [here](https://github.com/home-assistant/core/pull/84548), including a short demo clip.
(Waiting for this PR to be accepted and new version of the library to be published before HA's PR can be submitted.)

**Comment by OnFreund** [comment]
Thanks @amitfin, new version released here: https://pypi.org/project/pycoolmasternet-async/0.1.5/

Please note the the HA PR is unlikely to pass review in its current implementation - you'll most likely be asked to use separate entities (probably a switch for the filter state and sensor for the error code) rather than attributes and custom services.

**Comment by amitfin** [comment]
Thanks @OnFreund.
I was also debating between the 2 different approaches. Since Climate has many attributes, it seemed more aligned to add attributes than creating separate entities. In addition, the default naming for the units is not descriptive, so it's most likely that "friendly_name" (or even the entity_id) gets changed. By having multiple entities, the renaming process becomes tedious (number of units times number of entities).
As for the custom service, I don't see many options here, regardless of the entity which is used for the service call. (But I might be missing something here, so please let me know if you have something concrete in mind.)
image

**Comment by OnFreund** [comment]
The core team has shifted to preferring separate entities over the last few years, and I think they even mentioned somewhere that climate, if designed today, would have been several entities by itself.

As for naming - don't worry about it. With the new naming schema, all you have to do is give your entity a "relative" name, and the prefix will be taken from the device (so if you use the name "Filter" and the user renames l1_111 to "Bedroom A/C", the resulting entity name will be "Bedroom A/C Filter"). You only rename once per device.

If clean filter is a switch - you don't need a custom service. You can simply use the regular turn off service (you just have to prevent the user from turning it on, because that doesn't make sense - it can only be marked as on by coolmaster itself).

**Pull request merged**
