### PR TITLE
swing support

### PR DESCRIPTION
**Pull request by amitfin**
Adds a swing support, so we can also exposed it in Home Assistant.
Note that the change is longer because of a simple indentation inside _make_request().

The change was tested by using the following script:
```
import asyncio
from coolmasternet import CoolMasterNet

async def test():
    for key, unit in (await (CoolMasterNet("192.168.1.98").status())).items():
        print(f"{key}: {unit.swing}")

asyncio.run(test())
```

### CODE REVIEW

**Comment by amitfin** [comment]
Additional explanation about the change:
1) An async factory function was created for CoolMasterNetUnit since the constructor can't by async.
2) The factory function gets the additional data requires for the swing mode.
3) The new flow creates a burst of requests, one per unit. However, there is a limit of 4 concurrent connections on the aserver (based on the documentation). So, we limit the amount of concurrent reads to 3 (to be on the safe side), which is done using the semaphore.

**Comment by amitfin** [comment]
(BTW, I already made the corresponding changes in coolmaster integration at Home Assistant core, but one step at a time.)

**Comment by amitfin** [comment]
(For reference, Home Assistant Core PR can be found [here](https://github.com/home-assistant/core/pull/82809).)

**Review by OnFreund — COMMENTED** [review]
Thanks @amitfin. This looks good to me, but I do have two thoughts:
1. Maybe we should allow forcing a no-swing mode? Deployments without swing are "taxed" both on start, and every time a unit object is instantiated
2. Something feels a bit off about the way units are created with most of the information passed from the outside, and the swing mode queried inside. I'm sure there's a better alternative but I can't think of one

**Comment by amitfin** [comment]
Thanks @OnFreund!

> 1. Maybe we should allow forcing a no-swing mode? Deployments without swing are "taxed" both on start, and every time a unit object is instantiated

- Disabled swing mode support by default (please let me know if you think it should be enabled by default).

> 2. Something feels a bit off about the way units are created with most of the information passed from the outside, and the swing mode queried inside. I'm sure there's a better alternative but I can't think of one

- Changed `CoolMasterNetUnit.create()` to do both reads, unless we already provide the data (optimization).

**Comment by OnFreund** [comment]
Thanks @amitfin!

**Comment by OnFreund** [comment]
New release here:
https://pypi.org/project/pycoolmasternet-async/0.1.4/

**Pull request merged**
